### ISSUE TITLE
Positional audio isn't correct

### ISSUE THREAD

**Issue by icculus** [icculus/mojoAL#4]
As for the transition: yes, this code _also_ has problems. It's already an extremely naive approach, and on top of that, there's clearly some incorrect math somewhere causing that jarring transition. Fixing that is on the TODO list (but I'm going to split this comment into a second bug so there's an actual place we're tracking that change).

_Originally posted by @icculus in https://github.com/icculus/mojoAL/issues/2#issuecomment-898814119_

**Comment by adahlkvist-feral** [comment]
I believe you are overcomplicating your approach to calculating the angle between the "at" and the "position".

I think the correct way is to do the following:

1) Take the position vector and subtract the listener position, store in a vector called V
2) Let a = Dot(V, Up)
3) Remove upwards component of V by doing V = V - a * Up
4) V will now lie in the plane with your "at" vector
5) Use the cross product to calculate the angle.

**Comment by adahlkvist-feral** [comment]
Actually the above code might not always work, you need to clamp the thing you put into SDL_acosf from -1 to 1 otherwise you get NaN issues when the float rounding goes ever so slightly above 1 sometimes.

**Comment by adahlkvist-feral** [comment]
Also I am suspicious of the use of SIMD here, it seems like overkill for such a simple calculation

**Comment by adahlkvist-feral** [comment]
Upon further reflection, I think the right code would look like this:

```
	// AJD 12-Apr-23 - Get position relative to the listener
	ALfloat V[3];
	SDL_memcpy(V, position, sizeof(V));
	ALfloat a = dotproduct(V, up);

	// Remove upwards component so it lies completely within the horizontal plane.
	V[0] -= a * up[0];
	V[1] -= a * up[1];
	V[2] -= a * up[2];  

	// Calculate angle
	ALfloat mags = magnitude(at) * magnitude(V);
	ALfloat cosAngle = (mags == 0.0f) ? 0.0f : (dotproduct(at, V) / mags);
	cosAngle = fmaxf(fminf(cosAngle, 1.0f), -1.0f);
	radians = SDL_acosf(cosAngle);

	// Get "right" vector
	ALfloat R[3];
	xyzzy(R, at, up);

	// If it's facing right, then it's positive, if it's facing left, then it's negative.
	if (dotproduct(R,V) < 0.0f)
	{
		radians = -radians;
	}
	```

**Comment by ericoporto** [comment]
A person made a fork with an alternative calculation that appears related to this

https://github.com/Helco/mojoAL/commit/f5db374adc0d1254876450ca97a259ef9990922b

**Comment by mcb2003** [comment]
> A person made a fork with an alternative calculation that appears related to this
> 
> [Helco@f5db374](https://github.com/Helco/mojoAL/commit/f5db374adc0d1254876450ca97a259ef9990922b)

I tested this, can confirm it fixed the issues I was having with very jarring transitions. My test application places two stereo sources in front of the listener, then spins the listener around. It works great with this fork. Any chance this patch could be merged?

**Comment by icculus** [comment]
The patch in a9e2f30b04f10df1912d06ff5a610edda4677ba5 is based on @Helco's work (thanks!).

The original patch was always converting to source-relative mode and didn't have the SIMD versions implemented, so I tweaked and updated it.

It's possible this math is _also_ wrong (and/or I screwed it up, either in updating it or in the SIMD translation), so PLEASE test the latest and report back!

**Comment by icculus** [comment]
> The patch in a9e2f30 is based on Helco's work (thanks!).

(Actually, reading back, this was @adahlkvist-feral's work originally.)

**Comment by Helco** [comment]
3D positions seem to have rotated 90° in the new commit compared to my fork. But I also introduced a copy-paste error in my fork and already had to fiddle around with orientations.
Maybe just a gotcha for someone unlucky enough to use the fork.

Thanks again, also to [adahlkvist-feral](https://github.com/adahlkvist-feral) whose  code I stole for the fork

**Comment by Helco** [comment]
I checked that the current sound orientations seem to be same between MojoAL and OpenAL-Soft, so the rotation must have been a bug in my fork.
